version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 449095351082.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=449095351082.dkr.ecr.us-east-1.amazonaws.com/box-office-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"box-office-repo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Docker inspect"
      - docker inspect $REPOSITORY_URI:$IMAGE_TAG | tee docker_inspect.json
      - echo "ECR manifest"
      - aws ecr batch-get-image --repository-name box-office-repo --image-ids imageTag=$IMAGE_TAG --query 'images[0].imageManifest' --output text | jq '.' | tee ecr_manifest.json
artifacts:
  files:
    - imagedefinitions.json
    - docker_inspect.json
    - ecr_manifest.json